apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage for CloudNomster
  annotations:
    github.com/project-slug: CloudNomster/backstage
    argocd/app-name: backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: group:team-nomster
  lifecycle: production
  dependsOn:
    - name: homelab
