apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helmbackstage
  description: Backstage Helm chart
  annotations:
    github.com/project-slug: CloudNomster/helm-backstage
    argocd/app-name: backstage
    # 'backstage.io/kubernetes-id': backstage
    # backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: 'app=backstage'
    # backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:team-nomster
  lifecycle: production
